### ISSUE TITLE
4. 테스트 분류에 test_clean.csv 파일이 없습니다.

### ISSUE THREAD

**Issue by jinnypt** [NLP-kr/tensorflow-ml-nlp#1]
4번 항목의 data_in 폴더에 test_clean.csv 파일이 누락된거 같네요~

**Comment by Taekyoon** [comment]
@jinnypt 

안녕하세요, 저희 자연어처리 책을 읽어주셔서 감사합니다.

말씀하신 내용을 확인 해봤는데요. 
현재 github repository에서 4장 `data_in` 폴더 안에 `test_clean.csv` 파일이 없는 걸 확인했습니다. 
바로 준비대는대로 올려두도록 하겠습니다.

만약에 지금 바로 test_clean.csv 파일을 활용하시고 싶으시다면,
4장에 `4.1.2.EDA&preprocessing.ipynb`을 실행해보시면 됩니다.
이 실습파일에서 `test_clean.csv`파일을 `data_in`폴더로 저장해줍니다.

좋은 이슈 올려주셔서 감사하고 자연어 처리 공부 화이팅하시기 바랍니다^^

**Comment by Taekyoon** [comment]
4장 `data_in` 폴더에 `test_clean.csv` 파일 추가 완료.
