### ISSUE TITLE
Transformer 예제 Time 관련 질문

### ISSUE THREAD

**Issue by frog13579kr** [NLP-kr/tensorflow-ml-nlp#10]
"야" 라는 내용을 넣을시
"네" 라는 답변을 받습니다.

이 과정에서 data.py 에서
for v in value:
        sentence_string = [dictionary[index] for index in v['indexs']]

이부분에서 약 26s 정도 소요가 됩니다.
sentence_string 이 아닌 for문 첫 진입시에 소요됩니다.

이는 generator object 의 첫 yield 값을 읽어오는데 걸리는 시간으로 예상 되는데

정확한 이유는 잘 모르겠습니다.

1. 저만 이러한 현상이 생기는건가요? 아니면 원래 그러한 코드인가요?
2. 해결방안은 무엇입니까?

빠른 도움을 부탁드립니다.

**Comment by Taekyoon** [comment]
네 안녕하세요. 

저희가 먼저 독자님 문제를 확인했는데요. 
문제에 대한 원인을 파악하는데 앞서 몇 가지 확인하고자 합니다.

1. 우선 컴퓨터 사양과 환경은 어떻게  되시나요? (예. intel i5 2.5Ghz, 4GB ram, nvidia 1080-ti, linux 16.04 버전 등)
2. 저러한 문제가 나오는데 어떠한 실행 과정을 거치셨나요? (가능한한 상세하게 설명을 해주시면 보다 나은 답변을 드릴 수 있을 것 같습니다.\
3. 혹시 프로젝트 코드에 수정을 하신 부분이 있나요?
4. 시간 소요는 어떻게 확인해보셨나요?

네 가지 질문에 대한 답변을 주시면 보다 정확한 문제에 대한 해답을 드릴 수 있을 것 같습니다.

**Comment by frog13579kr** [comment]
> 네 안녕하세요.
> 
> 저희가 먼저 독자님 문제를 확인했는데요.
> 문제에 대한 원인을 파악하는데 앞서 몇 가지 확인하고자 합니다.
> 
> 1. 우선 컴퓨터 사양과 환경은 어떻게  되시나요? (예. intel i5 2.5Ghz, 4GB ram, nvidia 1080-ti, linux 16.04 버전 등)
> 2. 저러한 문제가 나오는데 어떠한 실행 과정을 거치셨나요? (가능한한 상세하게 설명을 해주시면 보다 나은 답변을 드릴 수 있을 것 같습니다.\
> 3. 혹시 프로젝트 코드에 수정을 하신 부분이 있나요?
> 4. 시간 소요는 어떻게 확인해보셨나요?
> 
> 네 가지 질문에 대한 답변을 주시면 보다 정확한 문제에 대한 해답을 드릴 수 있을 것 같습니다.



관심답변 감사합니다.
1. 윈도우10
    cpu: i7-4800MQ
    ram: 8gb
    gpu: Nvidia Geforce GTX 765M
    
2.현재 사용 방법 : anaconda 가상환경에 모듈설치를 하여 eclipse 에서 pydev 로 구동중.
                             anaconda 내의 python ~~~.py "야" 이러한 방법으로도 마찬가지의 결과가 출력됨.
                             predict.py 관련 내용을 flask 서버에 올리고 spring 서버에서 입력값을 받아 
                             flask 로 전달 후 answer 를 return 받아 출력 중.

3. flask 를 통해 등록하고 spring 에서 입력받은 text 를 flask 에 전달 후 결과값 return 받았습니다.
    수정부분
     =predict.py=
     ===>삭제
     arg_length = len(sys.argv)
     if(arg_length < 2):
             raise Exception("Don't call us. We'll call you")
      ====>삭제
      input = ""
      for i in sys.argv[1:]:
              input += i 
              input += " "
       print(input)
      ===>삭제 이유 : string 형태로 "야" 라는값을 flask 의 post 에서 생성하여 
                                  predic_input_enc, predic_input_enc_length = data.enc_processing([text], char2idx)
                                  이부분에 input 대신 text 로 바꿔 바로 넣게 하였습니다.
4.
   st = t.time()
   for v in value:
            dt = t.time()
            print("진입 소요시간:{0}".format(dt-st))
            sentence_string = [dictionary[index] for index in v['indexs']]
   ddt = t.time()
   print("종료 까지 걸린 시간:{0}".format(ddt-st))


* 추가로 남깁니다.
   시행 코드는 현재 github 에 올리신 소스가 아닌 책 마지막 에 있는 code 를 보고 작성하였습니다.
   참고 부탁드립니다.
   github 에 올려주신 소스로 구동시 약 5-10초정도 더 개선된 속도로 나오는것을 확인하였습니다.

**Comment by frog13579kr** [comment]
> 네 안녕하세요.
> 
> 저희가 먼저 독자님 문제를 확인했는데요.
> 문제에 대한 원인을 파악하는데 앞서 몇 가지 확인하고자 합니다.
> 
> 1. 우선 컴퓨터 사양과 환경은 어떻게  되시나요? (예. intel i5 2.5Ghz, 4GB ram, nvidia 1080-ti, linux 16.04 버전 등)
> 2. 저러한 문제가 나오는데 어떠한 실행 과정을 거치셨나요? (가능한한 상세하게 설명을 해주시면 보다 나은 답변을 드릴 수 있을 것 같습니다.\
> 3. 혹시 프로젝트 코드에 수정을 하신 부분이 있나요?
> 4. 시간 소요는 어떻게 확인해보셨나요?
> 
> 네 가지 질문에 대한 답변을 주시면 보다 정확한 문제에 대한 해답을 드릴 수 있을 것 같습니다.

#추가 사항 으로 글을 남깁니다.
질문의 길이 와 상관없이 답변의 길이가 길어질수록 결과 를 받아보는시간은 더더욱 증가합니다.
예를들어
"야" 라는 값을 넣고
응답 값이 "네 안녕하세요 오랫만 입니다" 라고 한다면 
이때는 약 35초

"야" 라는 값을 넣고
응답 값이 "네" 라고 한다면
이떄는 약 8초

이렇게 됩니다.

transformer 가 lstm 으로 작성했을시보다 빠른처리가 가능하다고 알고있는데
이렇게 답변 이 길어진다면 챗봇으로써의 기능만 할뿐 실용성이 무척 떨어질것 같기에
제 환경이 잘못된것인지
아니면 개선의 여지가 있는 부분인건지 궁금합니다~

**Comment by frog13579kr** [comment]
자답 입니다만
컴퓨팅 파워(CPU) 의 클럭을 높이고 나니 향상된 결과를 얻을수 있었습니다.

그렇다해도, 소스 상으로는 개선의 여지가 있는지 궁금합니다.

**Comment by Taekyoon** [comment]
늦은 답변 죄송합니다.

우선 설명하신 내용 살펴봤고요.
`sentence_string = [dictionary[index] for index in v['indexs']]` 부분에서 성능이 안나는 문제를 봐야하는데

혹시 이 부분에 대한걸 더미로 작성해서 돌려보시는 건 어떨까요?

예를 들어 
```
dictionary = {'0': 'pad', '1': '사과', '2':'는' .... , '999': '맛있' ...}
v = {'indexs': [1,3,5,2,6, 3, 7, ... , 0,0,0]}
sentence_string = [dictionary[index] for index in v['indexs']]
```

위와 같이 별도로 이렇게 실행을 해도 비슷한 성능이 나오는지 확인할 수 있을까요?
실행을 하기전에 확인하실 부분이 있습니다.

1. dictionary를 print하셔서 실제로 dictionary 변수 값이 제가 올려드린 예시와 비슷한지 확인해주세요
2. v['indexs']를 print하셔서 실제로 v['indexs'] 변수 값이 제가 올려드린 에시와 비슷한지 확인해주세요

이렇게 한번 해보시고 어떠신지 알려주세요.
이렇게 확인하는 이유는 말씀하신 문제가 있는 코드라인에서 시간이 실제로 오래걸리는지 별도로 확인하고자 함입니다.

**Comment by Taekyoon** [comment]
@frog13579kr 님 문제를 확인했습니다.
지금 모델 예측 시 늦어지는 문제는 predict.py 를 실행할 때 model 그래프를 매번 메모리에 올린 다음 inference를 하기 때문에 그렇습니다. 따라서, 현재 predict.py의 성능 문제는 모델 연산하는 부분과 전처리 후처리 부분에 문제가 있지 않고 모델을 연산하기 직전 메모리 올리는 부분에 대한 문제로 보시면 될 것 같습니다.
만약에 모델을 실제로 deploy해서 활용해보시고 싶으시다면 다음 페이지를 보실 것을 권해드립니다.

https://guillaumegenthial.github.io/serving-tensorflow-estimator.html

아무쪼록 도움이 되셨길 바랍니다.

감사합니다.

**Comment by Taekyoon** [comment]
@changwookjun @frog13579kr  

위 내용에 대해서는 Wiki FAQ에 내용을 남겨 두었습니다.
이 이슈에 대한 스레드는 여기서 종료하도록 하겠습니다.
