### ISSUE TITLE
1. Intro 에서 2가지 이슈를 만났습니다.

### ISSUE THREAD

**Issue by sociengineer** [NLP-kr/tensorflow-ml-nlp#11]
안녕하세요 책을 구입해 읽고 있는 독자입니다. 환경 구축 설치 중에 2가지 에러가 있어 문의드립니다.

1. pip install -r requirements.txt 설치 중 에러 발생합니다. 이 에러를 어떻게 해결할 수 있을까요?

ERROR: Complete output from command /Users/apple/anaconda3/envs/pr_tensorflow/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/4h/6q121zpj2xg3rj65pq_v0snw0000gn/T/pip-install-ezyc_w01/JPype1/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/4h/6q121zpj2xg3rj65pq_v0snw0000gn/T/pip-wheel-3epqkql9 --python-tag cp37:
  ERROR: /Users/apple/anaconda3/envs/pr_tensorflow/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'use_scm_version'
......
native/common/include/jpype.h:82:10: fatal error: 'map' file not found
  #include <map>
           ^~~~~
  1 warning and 1 error generated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for JPype1

2. 1번 에러 때문인지 몰라도 github에서 다운 받은 실습 프로젝트 폴더에서 jupyter notebook 명령어가 실행되지 않습니다.
-bash: jupyter: command not found

**Comment by changwookjun** [comment]
대부분 책저자들이 맥이나 리눅스 환경이여서 
window 환경에서는 requirements.txt를 실행하면 문제가 발생할수도 있을듯 합니다. 


해당 이슈를 좀 찾아보니 https://needjarvis.tistory.com/224 이쪽에 설명이 자세히 나와 있는듯 합니다. 

책에 나온대로 한번에 인스톨 하지 마시고 윈도우에서는 파일안에 들어 있는것을 하나씩 인스톨 하시길 추천 드립니다.



JPype 같은 경우에는 konlpy를 설치할때 필요한 부분 입니다. 

https://konlpy-ko.readthedocs.io/ko/v0.4.3/install/#id2

위는 윈도우 설치 가이드 입니다.

**Comment by sociengineer** [comment]
아 제가 운영체제 환경을 말씀 안드렸는데, 윈도우가 아니라 Mac 환경입니다.

**Comment by sociengineer** [comment]
첫번째 에러는 다음 링크로 해결했습니다.
https://github.com/konlpy/konlpy/issues/224

두번째 에러인 노트북 실행 에러는 제가 노트북을 설치 안해서 발생하는 문제인가요?
---------
anaconda 설치하면 주피터도 같이 설치된다는데 저는 무슨 문제가 있어서 설치가 안되었나봐요
pip로 직접 설치하는 방법으로 해결 되었습니다.
https://jupyter.org/install
