### ISSUE TITLE
64페이지 오류 문의

### ISSUE THREAD

**Issue by bigsea00001** [NLP-kr/tensorflow-ml-nlp#12]
밑에서 두번째 예제에서
sentence = [text_data[3]]
print(tfidf_vectorizer.transfrom(text_data).toarray()) 라고 되어 있는 부분에서 
'text_data'를 'sentence'로 변경해야 하는 것이 아닌지 문의 드립니다.

**Comment by reniew** [comment]
해당 이슈는 문장 하나만 확인하기 위한 테스트 과정이므로
`text_data`에서 `sentence`로 변경하는것이 적절합니다.
좋은 지적 감사합니다
