### ISSUE TITLE
121 페이지 예제에서 '비' 단어가 빠진 이유 문의

### ISSUE THREAD

**Issue by bigsea00001** [NLP-kr/tensorflow-ml-nlp#13]
sent = ("휴일 인 오늘 도 서쪽 을 중심 으로 폭염 이 이어졌는데요, 내일 은 반가운 비 소식 이 있습니다.", "폭염 을 피해서 휴일 에 놀러왔다가 갑작스런 비 로 인해 망연자실 하고 있습니 다.")

위에는 '비' 단어가 첫번째, 두번째 요소에 모두 들어 있는데, 아래에는 왜 '비' 단어가 들어가지 않는 것인지 문의 드립니다. 감사합니다!!

{'갑작스런': 1.4054651081081644, '내일': 1.4054651081081644, '놀러왔다가': 1.4054651081081644, '망연자실': 1.4054651081081644, '반가운': 1.4054651081081644, '서쪽': 1.4054651081081644, '소식': 1.4054651081081644, '오늘': 1.4054651081081644, '으로': 1.4054651081081644, '이어졌는데요': 1.4054651081081644, '인해': 1.4054651081081644, '있습니': 1.4054651081081644, '있습니다': 1.4054651081081644, '중심': 1.4054651081081644, '폭염': 1.0, '피해서': 1.4054651081081644, '하고': 1.4054651081081644, '휴일': 1.0}

**Comment by rainmaker712** [comment]
안녕하세요, 독자님

"비"에 대한 단어가 왜 안나오는지 추가로 확인 해 보겠습니다.

현재 저도 다시 테스트하고 추가로 비라는 단어를 3번 이상 반복했는데도 나오지 않는 현상이 있어서 검토 중입니다.

![image](https://user-images.githubusercontent.com/10111029/61167074-dd0dc500-a573-11e9-9908-5f1d06c5b23a.png)

**Comment by changwookjun** [comment]
sklearn 에 TFIDF API에서는 한글 한음절 (예: "비", "눈" 등) 과 알파벳 한개(예: "a", "t"등) 은 분석 내용에서 포함되지 않아 위와 같은 결과가 발생하고 있습니다.

API 특성으로 보입니다.

**Comment by rainmaker712** [comment]
API확인 결과, 특이사항이 발견되지 않았습니다. 한글자로 된 글씨는 출력이 되지 않는 듯 합니다.

https://github.com/scikit-learn/scikit-learn/blob/1495f6924/sklearn/feature_extraction/text.py#L1147

추가 질문 없으시면 클로징 하겠습니다.
