### ISSUE TITLE
122페이지 자카드 유사도 예제문장 오류 문의

### ISSUE THREAD

**Issue by bigsea00001** [NLP-kr/tensorflow-ml-nlp#14]
예제 문장 벤다이어그램을 통해 보면 교집합의 갯수가 5개이고 왼쪽 벤다이어 그램 안의 원소의 갯수는 12개입니다. 그럼에도

벤다이어그램 바로 밑에 설명이 교집합 6개, 와 B의 합집합 개수는 24라고 설명되어져서 합집합의 개수는 24(6+11+7)이므로 자카드 유사도는 6/24 라고 설명되어 있습니다. 

이것을 교집합이 5개, 합집합의 개수는 24(5+12+7) 이므로 자카드 유사도는 5/24 로 수정되어야 하는 것이 맞는지 문의 드립니다.

**Comment by rainmaker712** [comment]
@bigsea00001 안녕하세요, 관련 사항에 대해서 답변 해주셔서 감사합니다.

독자님이 말씀하신대로 합집합의 갯수 24(5+12+7)이 맞습니다. 

관련 사항 수정에 반영하겠습니다.

**Comment by rainmaker712** [comment]
관련사항 반영 완료
