### ISSUE TITLE
형태소 분석에서 문장의 공백 제거

### ISSUE THREAD

**Issue by hccho2** [NLP-kr/tensorflow-ml-nlp#17]
페이지 290과 6.3 seq2seq\data.py에 보면

morph_tokenized_sentences = [okt.morphs(s.replace(' ', '')) for s in sentences]
에서
s.replace(' ', '')과 같이 문장에서 공백을 제거 후, 형태소 분석을 하고 있습니다.
공백 제거를 하는 이유가 있나요?

형태소 분석기의 성능을 측정하기 위해, 일부러 공백을 제거한 후 테스트 하기도 하지만,
여기서 공백을 제거할 필요가 있을까요?

공백 제거:
print(okt.morphs(sentences[20].replace(' ', '')))
['가스', '비비', '싼데', '감기', '걸리겠어']

공백 제거 없이:
print(okt.morphs(sentences[20]))
['가스', '비', '비싼데', '감기', '걸리겠어']

예를 하나 더 들면
> " ".join(morph_analyzer.morphs('3박4일 정도 놀러가고 싶다'.replace(' ', '')))
--> '3 박 4일 정도놀러가고싶다'

> " ".join(morph_analyzer.morphs('3박4일 정도 놀러가고 싶다'))
--> '3 박 4일 정도 놀러 가고 싶다'

공백을 없애고 형태소 분석을 하면, "정도놀러가고싶다"를 하나의 형태소로 분석.

**Comment by Taekyoon** [comment]
안녕하세요.

공백 제거는 형태소 분석시 사용자가 입력한 다양한 띄어쓰기를 모두 고려하지 않도록 하기 위한 것입니다.
왜냐하면 사용자가 입력한 띄어쓰기는 경우에 따라 형태소 분석이 달라지고 이 결과는 모델 예측에 영향을 주게 됩니다.

위에 말씀하신 내용은 제가 보통 모델 학습 또는 예측 시 텍스트를 normalize 하는 경우에 활용합니다. 
하지만 입력 소스가 어디서 오는지에 따라서 띄어쓰기 공백제거를 할 수도 안 할 수도 있습니다.

만약에 개발을 고려하고 계신 상황이라면 형태소 분석에 사용자가 입력한 띄어쓰기를 반영하는지에 대한 선택은 @hccho2 님께서 개발 상황에 맞게 고려하여 하시면 될 것 같습니다.

감사합니다.

**Comment by hccho2** [comment]
데이터에 따라 선택하는 문제로 이해하면 되겠네요.
답변 감사합니다.
