### ISSUE TITLE
간단한 오류 확인

### ISSUE THREAD

**Issue by hccho2** [NLP-kr/tensorflow-ml-nlp#18]
page 125: 유클리디언 거리는 초록색선을 의미한다. ---> 검은색선
page 317 def Model(....) --> model(소문자)   <--- page 383에 있는 Model과 혼동인 듯.

**Comment by changwookjun** [comment]
page 125는 2쇄에 수정 반영 하였습니다. 

page 317는 확인 하였습니다. 

이렇게 알려주셔서 감사합니다. ~~^^
