### ISSUE TITLE
6장 encoding 에러

### ISSUE THREAD

**Issue by gyunggyung** [NLP-kr/tensorflow-ml-nlp#2]
6장에서 `python main.py` 실행시 아래와 같은 encoding 에러가 발생합니다.

6.3 장
```
Traceback (most recent call last):
  File "main.py", line 71, in <module>
    tf.app.run(main)
  File "C:\ProgramData\Anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "main.py", line 15, in main
    word2idx,  idx2word, vocabulary_length = data.load_vocabulary()
  File "C:\Users\hwnau\OneDrive\문서\NLP\tensorflow-ml-nlp-master\6.CHATBOT\6.3 seq2seq\data.py", line 233, in load_vocabulary
    for line in vocabulary_file:
  File "C:\ProgramData\Anaconda3\envs\tf_gpu\lib\codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb3 in position 38: invalid start byte
```
6.4 장
```
C:\Users\hwnau\OneDrive\문서\NLP\tensorflow-ml-nlp-master\6.CHATBOT\6.4 transformer>activate tf_gpu

(tf_gpu) C:\Users\hwnau\OneDrive\문서\NLP\tensorflow-ml-nlp-master\6.CHATBOT\6.4 transformer>python main.py
Traceback (most recent call last):
  File "main.py", line 100, in <module>
    tf.app.run(main)
  File "C:\ProgramData\Anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "main.py", line 17, in main
    char2idx, idx2char, vocabulary_length = data.load_vocabulary()
  File "C:\Users\hwnau\OneDrive\문서\NLP\tensorflow-ml-nlp-master\6.CHATBOT\6.4 transformer\data.py", line 375, in load_vocabulary
    for line in vocabulary_file:
  File "C:\ProgramData\Anaconda3\envs\tf_gpu\lib\codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbb in position 28: invalid start byte
```

핵심에러로 한글 깨짐과 관련이 있는 거 같습니다.
```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbb in position 28: invalid start byte
```

구글링을 해서 utf-8을 에러 문제를 
```
with open(DEFINES.vocabulary_path, 'r', encoding='utf-8',errors='replace') as vocabulary_file:

#바뀐 부분 에러를 무시하는 코드입니다.
errors='replace'
```

을 사용해서 해결하면 새로운 에러가 발생합니다.  

```
Traceback (most recent call last):
  File "main.py", line 71, in <module>
    tf.app.run(main)
  File "C:\ProgramData\Anaconda3\envs\tf_gpu\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "main.py", line 21, in main
    train_input_dec, train_input_dec_length = data.dec_input_processing(train_label, word2idx)
  File "C:\Users\hwnau\OneDrive\문서\NLP\tensorflow-ml-nlp-master\6.CHATBOT\6.3 seq2seq\data.py", line 95, in dec_input_processing
    sequence_index = [dictionary[STD]] + [dictionary[word] for word in sequence.split()]
  File "C:\Users\hwnau\OneDrive\문서\NLP\tensorflow-ml-nlp-master\6.CHATBOT\6.3 seq2seq\data.py", line 95, in <listcomp>
    sequence_index = [dictionary[STD]] + [dictionary[word] for word in sequence.split()]
KeyError: '여기'
```

위와 같은 에러가 발생합니다.

```
sequence_index = [dictionary[STD]] + [dictionary[word] for word in sequence.split()]
# 여기서 한글 문자를 받을 수 없는 것으로 보입니다.
```

**Comment by reniew** [comment]
이슈 감사합니다.
혹시 어떤환경에서 돌리신건지 알려주실 수 있으신가요?

**Comment by changwookjun** [comment]
C:\ProgramData\Anaconda3  윈도우 인거 같습니다.

**Comment by gyunggyung** [comment]
네, 그리고 tensorflow version은 '1.12.0'입니다.

**Comment by changwookjun** [comment]
안녕하세요 . 전창욱 입니다. 
data_in 안에 있는 tf.app.flags.DEFINE_string('vocabulary_path', './data_out/vocabularyData.voc', 'vocabulary path')  vocab파일을 삭제하고 

현재 github에 올라가 있는 소스와 같이 아래와 같이 한번 사전 파일 부터 다시 생성 해서 해보시겠어요 ?


# 최초 사전 파일을 만드는 함수이며 파일이 존재 한다면 불러오는 함수이다.
def load_vocabulary():
    vocabulary_list = []
    # 사전 파일의 존재 유무를 확인한다.
    if (not (os.path.exists(DEFINES.vocabulary_path))):
        if (os.path.exists(DEFINES.data_path)):
            data_df = pd.read_csv(DEFINES.data_path, encoding='utf-8')
            question, answer = list(data_df['Q']), list(data_df['A'])
            if DEFINES.tokenize_as_morph:  
                question = prepro_like_morphlized(question)
                answer = prepro_like_morphlized(answer)
            data = []
            data.extend(question)
            data.extend(answer)
            words = data_tokenizer(data)
            words = list(set(words))
            # 데이터 없는 내용중에 MARKER를 사전에 
            # 추가 하기 위해서 아래와 같이 처리 한다.
            # 아래는 MARKER 값이며 리스트의 첫번째 부터 
            # 순서대로 넣기 위해서 인덱스 0에 추가한다.
            # PAD = "<PADDING>"
            # STD = "<START>"
            # END = "<END>"
            # UNK = "<UNKNWON>"     
            words[:0] = MARKER
        # 사전 리스트를 사전 파일로 만들어 넣는다.
        with open(DEFINES.vocabulary_path, 'w', encoding='utf-8') as vocabulary_file:
            for word in words:
                vocabulary_file.write(word + '\n')

    # 사전 파일이 존재하면 여기에서 그 파일을 불러서 배열에 넣어 준다.
    with open(DEFINES.vocabulary_path, 'r', encoding='utf-8') as vocabulary_file:
        for line in vocabulary_file:
            vocabulary_list.append(line.strip())

    word2idx, idx2word = make_vocabulary(vocabulary_list)
    # 두가지 형태의 키와 값이 있는 형태를 리턴한다. 
    # (예) 단어: 인덱스 , 인덱스: 단어)
    return word2idx, idx2word, len(word2idx)

**Comment by gyunggyung** [comment]
안녕하세요. vocab을 포함한 기존에 있는 것들을 전부 삭제하고 

`git clone` 후 정상 동작을 하는 거 같습니다. 감사합니다 :)

**Comment by gyunggyung** [comment]
안녕하세요. 6.4 장에서 동일한 오류가 발생합니다. 

6.3 장과 달리 재설치를 하고 vocab파일을 삭제하여도 encoding 에러가 발생합니다.

`data.py`에서 인코더를 바꾸고 try문을 써서 오류가 안 나오게 만들면 학습이 되고 loss가 계속해서 줄어듭니다.
```
    with open(DEFINES.vocabulary_path, 'r', encoding='euc-kr',errors='replace') as vocabulary_file:
        for line in vocabulary_file:
            vocabulary_list.append(line.strip())

...
        try:
            sequence_index = [dictionary[STD]] + [dictionary[word] for word in sequence.split()]
        except:
            print("ok") 

...

        try:
            sequence_index = [dictionary[STD]] + [dictionary[word] for word in sequence.split()]
        except:
            print("no") 

```

하지만 모든 값들(main.py 포함)의 answer이 전부 `<SOS>` 즉 STD만 나오는 문제가 발생합니다.
```
python predict.py sos 나는 잘생겼다
sos 나는 잘생겼다
answer:  <SOS>

python predict.py 너는 왜 그러니
너는 왜 그러니
answer:  <SOS>

python predict.py sos 그만해
sos 그만해
answer:  <SOS>
```

**Comment by changwookjun** [comment]
Try 문 제거 하시고 
data.py에 
def load_vocabulary():  


        # 사전 리스트를 사전 파일로 만들어 넣는다.
        with open(DEFINES.vocabulary_path, 'w', encoding='utf-8') as vocabulary_file:
            for word in words:
                vocabulary_file.write(word + '\n')


위와 같이 한번 해보시겠어요 .

**Comment by gyunggyung** [comment]
해당 부분은 바꾸지 않았고 

def load_vocabulary():의 아래 부분에서 
```
    # 그 파일을 불러서 배열에 넣어 준다.
    with open(DEFINES.vocabulary_path, 'r', encoding='utf-8') as vocabulary_file:
        for line in vocabulary_file:
            vocabulary_list.append(line.strip())
```

인코딩 에러가 발생합니다.

`encoding='euc-kr',errors='replace'`을 추가해서 에러를 제거해였습니다.

**Comment by gyunggyung** [comment]
Ubuntu 에서는 오류가나지 않고 Windows 10 환경에서만 오류가 발생합니다. 왜 그럴까요??

**Comment by changwookjun** [comment]
그부분은 제가 작업한 부분이고 ubuntu 와  mac에서 환경 체크를 해서 windows에서 발생하는 이유는 현재 정확히는 모르나 리눅스는 기본적으로 utf-8이 default로 보입니다.   newhiwoong 님  어제 다시 받아서 잘되었는 것처럼 제가 소스를 올려 드릴테니 기존 소스를 삭제하고 사전을 삭제 하고 다시 해보시는게 좋아 보입니다. 이유는 저장 할때 windos는 utf-8로 저장을 안하면 문제가 발생하는 거 같습니다. 

소스는 read할때는 utf-8이 존재하는데  write할때 utf-8로 안해줘서 이슈가 발생하는것으로 보입니다.

**Comment by gyunggyung** [comment]
바뀐 후에 windows에서도 오류가 발생하지 않습니다.

감사합니다 👍
