### ISSUE TITLE
4.1.6과 4.1.7 문제가 발생하였습니다.

### ISSUE THREAD

**Issue by heozzi** [NLP-kr/tensorflow-ml-nlp#20]
4장 4.1.6 부분과 4.1.7 케글데이터 만드는 부분에서 아래와 같은 오류가 발생하였고 깃허브에 있는 코드를 넣어도 같은 오류가 발생하네요.

InvalidArgumentError: indices[115,133] = 82040 is not in [0, 74067)
	 [[node embedding_1/embedding_lookup (defined at C:\ProgramData\Anaconda3\envs\finance\lib\site-packages\keras\backend\tensorflow_backend.py:1228) ]]

해당 오류에 대해서 검색을 통해서 봐도 이해 하지 못해서 글을 남기게 되었습니다.
아래 파일은 오류를 전부 복사해서 놓았습니다 
감사합니다.
[error.docx](https://github.com/NLP-kr/tensorflow-ml-nlp/files/3480110/error.docx)

**Comment by Taekyoon** [comment]
안녕하세요. 
저희 책을 읽고 이슈를 올려주셔서 감사합니다. 
올려주신 이슈 내용은 확인하였습니다. 

우선 이슈에 올려주신대로 오류에 대한 설명이 가장 궁금하실 것 같아 
오류에 대한 내용을 먼저 말씀드리겠습니다.

```
말씀하신 오류는 Embedding lookup을 하는 상황에서 입력 index 값이 Embedding index 범위에 벗어난 값이 
들어와 발생한 오류 입니다. 
```

위 문제를 해결하기 위해서는 먼저 워드 임베딩의 인덱스와
임베딩 단어 사전 인덱스가 서로 일치하는지 확인하셔야 합니다.

보다 자세한 오류 원인에 대한 말씀을 드리기 위해선 
@heozzi 님이 구현하신 코드와 개발 환경 정보를 확인할 필요가 있습니다. 

감사합니다.

**Comment by heozzi** [comment]
안녕하세요. 
현재 IDE는 jupyter notebook 을 사용중입니다.
[kaggle_bag_of_popcorn(08.07)_CounterVecotr_RNN.zip](https://github.com/NLP-kr/tensorflow-ml-nlp/files/3485388/kaggle_bag_of_popcorn.08.07._CounterVecotr_RNN.zip)

입니다.

**Comment by Taekyoon** [comment]
> 안녕하세요.
> 현재 IDE는 jupyter notebook 을 사용중입니다.
> [kaggle_bag_of_popcorn(08.07)_CounterVecotr_RNN.zip](https://github.com/NLP-kr/tensorflow-ml-nlp/files/3485388/kaggle_bag_of_popcorn.08.07._CounterVecotr_RNN.zip)
> 
> 입니다.

공유해주셔서 감사합니다. 
우선 확인 후에 말씀드리겠습니다.

**Comment by Taekyoon** [comment]
위 문제는 입력한 인덱스가 임베딩 사이즈보다 커져 lookup이 제대로 되질 않아서 발생한 문제로 보입니다.
이 부분을 살펴보시면 좋을 듯 합니다.

**Comment by Taekyoon** [comment]
본 이슈에 대해서는 더 이상 진행되는 것으로 보이지 않아 close 하도록 하겠습니다.
