### ISSUE TITLE
403 forbidden 에러 관련 

### ISSUE THREAD

**Issue by sangjinhong** [NLP-kr/tensorflow-ml-nlp#21]
아래 명령을 실행하면 403 forbidden 에러가 발생하는데
해결방법이 있을까요???

환경을 windows 10 에서 anaconda 를 사용하고 python 3.6 을
사용하고 있습니다.

kaggle competitions download -c word2vec-nlp-tutorial

403 - Forbidden

**Comment by changwookjun** [comment]
API를 통해 다운로드하기 전에 대회 약관에 동의해야 할 수도 있습니다.

**Comment by sangjinhong** [comment]
해결을 했습니다. 감사합니다.
