### ISSUE TITLE
4.2 모델학습중 밸류에러나 어트리뷰트 에러.

### ISSUE THREAD

**Issue by yeonsookKwak** [NLP-kr/tensorflow-ml-nlp#25]
안녕하세요 4장 공부중에 est.train()하게 되면 value error나 repeatDataset 이 make_one_shot_iterator어트리뷰트 에러가 뜨는데 무슨 문제인지 잘 모르겠습니다. 
저는 구글 코랩에서 테스트 해보고 있고, 텐서플로 버전은 2.0.0입니다.

**Comment by changwookjun** [comment]
책 소스는  Tensorflow 1.10을 기반으로 테스트 되었습니다. 
TF 2.0으로는 안 될수 있습니다. 

Version을 다운 시켜서 테스트 해보세요 . 

아래 링크의 첫번째  부분을 보시면 하는 방법이 나와 있습니다. 

https://github.com/changwookjun/learningspoons/blob/master/Day5_2_seq2seq_Model.ipynb


좋은 하루 되세요 .

**Comment by yeonsookKwak** [comment]
답변주셔서 감사합니다. 
그런데 다운그레이드를 해서 테스트 해보아도 valueError가 발생하고 있습니다. 

 테스트 코드 :
# 파라미터 변수
RNG_SEED = 1234
BATCH_SIZE = 128
NUM_EPOCHS = 10000
VOCAB_SIZE = prepro_configs['vocab_size']
EMB_SIZE = 128
VALID_SPLIT = 0.2

from sklearn.model_selection import train_test_split
# 학습 데이터와 검증 데이터를 train_test_split()이용해서 나누기 
train_input, eval_input, train_label, eval_label = train_test_split(train_input_data, train_label_data, test_size =VALID_SPLIT, random_state = RNG_SEED )

# 전처리 학습을 위해 tf.data설정
def mapping_fn (X, Y):
  input, label = {'x':X}, Y
  return input, label

def train_input_fn():
  dataset = tf.data.Dataset.from_tensor_slices((train_input, train_label))
  dataset = dataset.shuffle(buffer_size = len(train_input))
  dataset = dataset.batch(BATCH_SIZE)
  dataset = dataset.map(mapping_fn)
  dataset = dataset.repeat(count = NUM_EPOCHS)

  iterator = dataset.make_one_shot_iterator()

  return iterator.get_next()

def eval_input_fn():
  dataset = tf.data.Dataset.from_tensor_slices((eval_input, eval_label))
  dataset = dataset.shuffle(buffer_size = len(eval_input))
  dataset = dataset.batch(BATCH_SIZE)
  dataset = dataset.map(mapping_fn)
  
  iterator = dataset.make_one_shot_iterator()

  return iterator.get_next()

def model_fn(features, labels, mode):

  TRAIN = mode = tf.estimator.ModeKeys.TRAIN
  EVAL = mode = tf.estimator.ModeKeys.EVAL
  PREDICT = mode = tf.estimator.ModeKeys.PREDICT

  # embedding layer선언
  embedding_layer = keras.layers.Embedding(
                                            VOCAB_SIZE,
                                           EMB_SIZE)(features['x'])

  dropout_emb = keras.layers.Dropout(rate=0.5)(embedding_layer)

  conv1 = keras.layers.Conv1D(
                              filters = 128,
                              kernel_size = 3,
                              padding = 'valid',
                              activation = tf.nn.relu)(dropout_emb)

  pool1 = keras.layers.GlobalAveragePooling1D()(conv1)

  conv2 = keras.layers.Conv1D(
                              filters = 128,
                              kernel_size = 4,
                              padding = 'valid',
                              activation = tf.nn.relu)(dropout_emb)

  pool2 = keras.layers.GlobalAveragePooling1D()(conv2)

  conv3 = keras.layers.Conv1D(
                              filters = 128,
                              kernel_size = 5,
                              padding = 'valid',
                              activation = tf.nn.relu)(dropout_emb)
  
  pool3 = keras.layers.GlobalAveragePooling1D()(conv3)

  concat = keras.layers.concatenate([pool1, pool2, pool3])

  hidden = keras.layers.Dense(250, activation=tf.nn.relu)(concat)
  dropout_hidden = keras.layers.Dropout(rate=0.5)(hidden)
  logits = keras.layers.Dense(1, name = 'logit')(dropout_hidden)
  logits = tf.squeeze(logits, axis = -1)

  if PREDICT:
    return tf.estimator.EstimatorSpec(mode=mode, predictions = {'prob':tf.nn.sigmoid(logits)})

  loss = tf.losses.sigmoid_cross_entropy(labels, logits)

  if EVAL:
    pred = tf.nn.sigmoid(logits)
    accuracy = tf.metrics.accuracy(lables, tf.round(pred))
    return tf.estimator.EstimatorSpec(mode = mode, loss = loss, eval_metric_ops = {'acc':accuracy})

  if TRAIN:
    global_step = tf.train.get_global_step()
    train_op = tf.train.AdamOptimizer(0.001).minimize(loss, global_step)

    return tf.estimator.EstimatorSpec(mode=mode, train_op = train_op, loss = loss)


cnn_est = tf.estimator.Estimator(model_fn, model_dir="/content/gdrive/My Drive/study/kaggle/hangeul/checkpoint/cnndeep")
cnn_est.train(train_input_fn)
#cnn_est.evaluate(eval_input_fn)


___________________________
INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': '/content/gdrive/My Drive/study/kaggle/hangeul/checkpoint/cnndeep', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f7ac72c1828>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/op_def_library.py in _apply_op_helper(self, op_type_name, name, **keywords)
    527                 as_ref=input_arg.is_ref,
--> 528                 preferred_dtype=default_dtype)
    529           except TypeError as err:

18 frames
ValueError: None values not supported.

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
ValueError: None values not supported.

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/op_def_library.py in _apply_op_helper(self, op_type_name, name, **keywords)
    544               raise ValueError(
    545                   "Tried to convert '%s' to a tensor and failed. Error: %s" %
--> 546                   (input_name, err))
    547             prefix = ("Input '%s' of '%s' Op has type %s that does not match" %
    548                       (input_name, op_type_name, observed))

ValueError: Tried to convert 'values' to a tensor and failed. Error: None values not supported.

**Comment by changwookjun** [comment]
해결이 되지 않았다니 안타깝네요. 코랩에서 작업하신다고 하니. 사용하시는 모든 파일과 환경인 구글 드라이브를  저에게 공유가능할까요. changwookjun@gmail.com 입니다.

**Comment by dhnam** [comment]
직접 tf2.0으로 바꿔본 버전입니다. 실행이 되는 것은 확인했고, 원본 코드와 약간 다르게 estimator를 쓰는 대신 직접 model.fit을 사용합니다. 링크는 Colab으로 연결됩니다.

[4.1장 영어 데이터 분류기](https://colab.research.google.com/gist/dhnam/394548bfe54680966c795f933032398c/text_classification.ipynb)

[4.2장 한국어 데이터 분류기](https://colab.research.google.com/gist/dhnam/e23b14ceb200768554345484d11f4e41/text_classification_ko.ipynb)

**Comment by changwookjun** [comment]
TF 2.0 자료 감사합니다. ^^
