### ISSUE TITLE
4.2.3 VOCAB_SIZE 관련 수정 사항

### ISSUE THREAD

**Issue by dhnam** [NLP-kr/tensorflow-ml-nlp#26]
4.2.3에서 `VOCAB_SIZE`가 `prepro_configs['vocab_size']`로 설정이 되어 있었는데, (불용어를 제시된 것이 아닌 온라인 상에서 찾을 수 있는 불용어를 쓰고, tf2.0버전으로 바꿔서 하는 등) 약간씩 코드를 바꿔서 하다 보니 이 부분과 관련해서 에러가 생깁니다.

4.1.6이나 4.1.7에서 그랬듯 `VOCAB_SIZE = prepro_configs['vocab_size'] + 1`로 설정해 주어야 할 것 같습니다.

해당 에러입니다.

```
InvalidArgumentError:  indices[5,3] = 43511 is not in [0, 43511)
	 [[node sequential_2/x/embedding_lookup (defined at <ipython-input-66-858fc70cce22>:5) ]]
```

**Comment by reniew** [comment]
안녕하세요.
우선 저희 코드에 관심을 가져 주셔서 감사합니다.
해당 이슈에 대해서는 다른 CNN, RNN (for english dataset)과 동일하게 vocab size에 대해서 Pad을 추가한 vocab size인 (기존 vocab_size+1)을 해줬어야 하는데 하지 않아서 lookup error가 나온 것 같습니다. 
말씀해주신 해결 방법대로 하면 해당 에러 해결  가능할 것 같습니다.
감사합니다.
