### ISSUE TITLE
5.2. '질문이 가득 찼을 때'

### ISSUE THREAD

**Issue by dhnam** [NLP-kr/tensorflow-ml-nlp#27]
이런 저런 오타들은 그러려니 하고 넘어가고 있는데, 웃기기까지 한 오타(오번역?)가 하나 있어서 제보합니다.

5.2. EDA & preprocessing 중

> `print('질문이 가득 찼을 때: {:.2f}%'.format(fullstop * 100))`

...아마도 questions with full stop을 의도한 것 같은데, 원래는 '마침표를 포함한 질문' 혹은 '마침표가 있는 질문'이 되야 할 것이 '질문이 가득 찼을 때'가 되어 있네요.

**Comment by changwookjun** [comment]
관심 가지시고 좋은 지적 너무 감사합니다.
