### ISSUE TITLE
랜덤 시드를 전부 설정해 준 것은 특정한 이유가 있나요?

### ISSUE THREAD

**Issue by dhnam** [NLP-kr/tensorflow-ml-nlp#28]
`train_test_split`등을 이용할 때 전부 random seed를 제공하고 있는데, 이를 지정한 것은 특정한 이유가 있나요? 아니면 읽는 사람이 책과 같은 결과를 얻을 수 있게 하기 위함인가요?

**Comment by Taekyoon** [comment]
네 맞습니다. 말씀하신것과 같이 책에서 나온 결과와 같게 유지하기 위한 것입니다.
Random seed를 주는 것은 모델 초기 랜덤 변수 생성을 일관되게 유지해줍니다.
