### ISSUE TITLE
4장 텍스트 분류 응용

### ISSUE THREAD

**Issue by cocoten** [NLP-kr/tensorflow-ml-nlp#31]
안녕하세요. 책을통해서 많은것들을 배울 수 있어서 너무 좋습니다.

4장에 영어,한글 텍스트 분류를 해 보고 있는데요.

예제로 한 것들은 모두 이진분류만 있는데 혹시 텍스트데이터를 여러가지 분류를 하는데 응용할려면 어떻게 코드를 수정해야 할까요??

100가지 이상의 분류를 해야하는데 지금의 예제코드로 CNN을 돌려보니 acc가 0으로 나오네요. 그리고 loss가 계속 증가하구요.

도움 주시면 감사하겠습니다.

**Comment by rainmaker712** [comment]
안녕하세요, 책 구매를 해 주시고 관심 가져주셔서 감사합니다.

100가지 이상의 분류를 해야하는 경우도 데이터가 충분하거나 한쪽으로 쏠리지 않는다면,
적어도 0 이상은 나와야 정상입니다.

가장 의심가는 부분은 마지막에 Loss 부분과 Logit부분이 현재는 이진분류로 세팅이 되 있어서,
Multi 분류로 하기 위해서 수정이 필요 할 듯 싶습니다.

혹시나 가능하시다면, 현재 100가지 이상 분류를 위해 사용한 Loss와 Logit부분과,
각 출력값을 Print로 확인 할 수 있을까요?

좀 더 자세한 분석이 필요 할 듯 합니다.

**Comment by cocoten** [comment]
def model_fn(features, labels, mode, params):
    TRAIN = mode == tf.estimator.ModeKeys.TRAIN
    EVAL = mode == tf.estimator.ModeKeys.EVAL
    PREDICT = mode == tf.estimator.ModeKeys.PREDICT

    embedding_layer = tf.keras.layers.Embedding(
                    VOCAB_SIZE,
                    EMB_SIZE)(features['x'])

    dropout_emb = tf.keras.layers.Dropout(rate = 0.2)(embedding_layer)
    
    conv = tf.keras.layers.Conv1D(
           filters=32,
           kernel_size=3,
           padding='same',
           activation=tf.nn.relu)(dropout_emb)
  
    pool = tf.keras.layers.GlobalMaxPool1D()(conv)

    hidden = tf.keras.layers.Dense(units=250, activation=tf.nn.relu)(pool)   


    dropout_hidden = tf.keras.layers.Dropout(rate=0.2)(hidden, training = TRAIN)
    logits = tf.keras.layers.Dense(units=495,activation=tf.nn.softmax)(dropout_hidden)
    
    if labels is not None:
        labels = tf.reshape(labels, [-1, 1])
        
    if TRAIN:
        global_step = tf.train.get_global_step()
        loss = tf.losses.softmax_cross_entropy(labels, logits)
        train_op = tf.train.AdamOptimizer(0.001).minimize(loss, global_step)

        return tf.estimator.EstimatorSpec(mode=mode, train_op=train_op, loss = loss)
    
    elif EVAL:
        loss = tf.losses.softmax_cross_entropy(labels, logits)
        pred = tf.nn.softmax(logits)
        accuracy = tf.metrics.accuracy(labels, tf.round(pred))
        return tf.estimator.EstimatorSpec(mode=mode, loss=loss, eval_metric_ops={'acc': accuracy})
        
    elif PREDICT:
        return tf.estimator.EstimatorSpec(
            mode=mode,
            predictions={
                'prob': tf.nn.softmax(logits),
            }
        )

이렇게 해서 돌렸는데요..


INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from data_out/checkpoint/cnn_model\model.ckpt-168750
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 168750 into data_out/checkpoint/cnn_model\model.ckpt.
INFO:tensorflow:loss = 0.0, step = 168751
INFO:tensorflow:global_step/sec: 3.797
INFO:tensorflow:loss = 0.0, step = 168851 (26.337 sec)
INFO:tensorflow:global_step/sec: 5.34503
INFO:tensorflow:loss = 0.0, step = 168951 (18.706 sec)
INFO:tensorflow:global_step/sec: 5.19871
INFO:tensorflow:loss = 0.0, step = 169051 (19.236 sec)
INFO:tensorflow:global_step/sec: 5.23143
INFO:tensorflow:loss = 0.0, step = 169151 (19.115 sec)
INFO:tensorflow:global_step/sec: 5.16163
INFO:tensorflow:loss = 0.0, step = 169251 (19.374 sec)
INFO:tensorflow:global_step/sec: 5.1293
INFO:tensorflow:loss = 0.0, step = 169351 (19.505 sec)
INFO:tensorflow:global_step/sec: 4.9146
INFO:tensorflow:loss = 0.0, step = 169451 (20.338 sec)
INFO:tensorflow:global_step/sec: 4.94527
INFO:tensorflow:loss = 0.0, step = 169551 (20.223 sec)

이렇게 올라고 있는데 잘못된걸까요? 



이렇게 시그모이드를 소프트 맥스로만 바꿔주면 되는건가요??

정확히 말씀 드리면 분류할 코드는 495여개 정도 되구요
데이터는 학습 3,000,000건 평가는 1,000,000건으로  준비했습니다.

그리고 필터 사이즈를 256으로 하면 지금 128보다 성능이 더 좋아질까요?
데이터가 많다보니 한번 테스트 하는데에도 시간이 상당히 걸리네요 ㅜㅜㅜ

**Comment by rainmaker712** [comment]
> def model_fn(features, labels, mode, params):
> TRAIN = mode == tf.estimator.ModeKeys.TRAIN
> EVAL = mode == tf.estimator.ModeKeys.EVAL
> PREDICT = mode == tf.estimator.ModeKeys.PREDICT
> 
> ```
> embedding_layer = tf.keras.layers.Embedding(
>                 VOCAB_SIZE,
>                 EMB_SIZE)(features['x'])
> 
> dropout_emb = tf.keras.layers.Dropout(rate = 0.2)(embedding_layer)
> 
> conv = tf.keras.layers.Conv1D(
>        filters=32,
>        kernel_size=3,
>        padding='same',
>        activation=tf.nn.relu)(dropout_emb)
> 
> pool = tf.keras.layers.GlobalMaxPool1D()(conv)
> 
> hidden = tf.keras.layers.Dense(units=250, activation=tf.nn.relu)(pool)   
> 
> 
> dropout_hidden = tf.keras.layers.Dropout(rate=0.2)(hidden, training = TRAIN)
> logits = tf.keras.layers.Dense(units=495,activation=tf.nn.softmax)(dropout_hidden)
> 
> if labels is not None:
>     labels = tf.reshape(labels, [-1, 1])
>     
> if TRAIN:
>     global_step = tf.train.get_global_step()
>     loss = tf.losses.softmax_cross_entropy(labels, logits)
>     train_op = tf.train.AdamOptimizer(0.001).minimize(loss, global_step)
> 
>     return tf.estimator.EstimatorSpec(mode=mode, train_op=train_op, loss = loss)
> 
> elif EVAL:
>     loss = tf.losses.softmax_cross_entropy(labels, logits)
>     pred = tf.nn.softmax(logits)
>     accuracy = tf.metrics.accuracy(labels, tf.round(pred))
>     return tf.estimator.EstimatorSpec(mode=mode, loss=loss, eval_metric_ops={'acc': accuracy})
>     
> elif PREDICT:
>     return tf.estimator.EstimatorSpec(
>         mode=mode,
>         predictions={
>             'prob': tf.nn.softmax(logits),
>         }
>     )
> ```
> 
> 이렇게 해서 돌렸는데요..
> 
> INFO:tensorflow:Calling model_fn.
> INFO:tensorflow:Done calling model_fn.
> INFO:tensorflow:Create CheckpointSaverHook.
> INFO:tensorflow:Graph was finalized.
> INFO:tensorflow:Restoring parameters from data_out/checkpoint/cnn_model\model.ckpt-168750
> INFO:tensorflow:Running local_init_op.
> INFO:tensorflow:Done running local_init_op.
> INFO:tensorflow:Saving checkpoints for 168750 into data_out/checkpoint/cnn_model\model.ckpt.
> INFO:tensorflow:loss = 0.0, step = 168751
> INFO:tensorflow:global_step/sec: 3.797
> INFO:tensorflow:loss = 0.0, step = 168851 (26.337 sec)
> INFO:tensorflow:global_step/sec: 5.34503
> INFO:tensorflow:loss = 0.0, step = 168951 (18.706 sec)
> INFO:tensorflow:global_step/sec: 5.19871
> INFO:tensorflow:loss = 0.0, step = 169051 (19.236 sec)
> INFO:tensorflow:global_step/sec: 5.23143
> INFO:tensorflow:loss = 0.0, step = 169151 (19.115 sec)
> INFO:tensorflow:global_step/sec: 5.16163
> INFO:tensorflow:loss = 0.0, step = 169251 (19.374 sec)
> INFO:tensorflow:global_step/sec: 5.1293
> INFO:tensorflow:loss = 0.0, step = 169351 (19.505 sec)
> INFO:tensorflow:global_step/sec: 4.9146
> INFO:tensorflow:loss = 0.0, step = 169451 (20.338 sec)
> INFO:tensorflow:global_step/sec: 4.94527
> INFO:tensorflow:loss = 0.0, step = 169551 (20.223 sec)
> 
> 이렇게 올라고 있는데 잘못된걸까요?
> 
> 이렇게 시그모이드를 소프트 맥스로만 바꿔주면 되는건가요??
> 
> 정확히 말씀 드리면 분류할 코드는 495여개 정도 되구요
> 데이터는 학습 3,000,000건 평가는 1,000,000건으로 준비했습니다.
> 
> 그리고 필터 사이즈를 256으로 하면 지금 128보다 성능이 더 좋아질까요?
> 데이터가 많다보니 한번 테스트 하는데에도 시간이 상당히 걸리네요 ㅜㅜㅜ

자세한 답변 감사드려요. 첫번째 말씀해주신 건 Loss가 올라간다고 하셨는데요,
올려주신 코드로 봐서는 이해가 가지 않는것 같습니다.

Acc가 0이 아니라 Loss가 0인듯 싶습니다. 제가 제대로 이해한게 맞는지 해서요.
(Loss가 0인 것도 조금 이상하긴 합니다)

+ 일반적으로 레이어 수를 더 깊게 하거나, 필터 사이즈 등을 키우면 성능이 오른다고 이야기는 하는데요,
그게 항상 정답이 없어서 실험을 해봐야 하는 어려움이 있습니다. 사실 그래서 AutoML이라는 테크닉이 나왔고요.

하지만, 데이터를 보니 충분히 많기 때문에  Layer등을 더 깊게 쌓으셔도 성능향상에 도움이 되실 듯 한데,

조금 더 정확히 알기 위해서, print(label) print(logit)쪽을 찍어봐 주실수 있나요?
텐서플로가 loss가 여러가지가 있는데요, print 값을 봐야 어떤 형태로 들어가는지 알 수 있을 듯 합니다.
(예를들어, label이 현재 onehot형태인지 아닌지 등)


이 아래를 참조 해 보시면, 어떠한 경우에 어떠한 loss를 사용하는지 다양한 설명들이 나와있는 듯 하네요.
https://stats.stackexchange.com/questions/207794/what-loss-function-for-multi-class-multi-label-classification-tasks-in-neural-n

**Comment by cocoten** [comment]
답변 감사드립니다.
사실은 지난주에 문의글을 올린 후에 코드를 일부 수정했습니다.
위에 말씀하신것처럼 loss 가 0 이 맞습니다. 제가 잘못적은거 같습니다.

위에 뎃글에 책에서 제시한 소스는 이진분류로 되어 있는거라서 제가 멀티분류를 할려면
바꿔야 하는 부분이 있는거 같아서  수정한 부분이

1. 기존에 sigmoid를 -> softmax로 변경 

2. 마지막 logits 에 dense unit을 멀티 분류의 개수에 맞게 495로 수정
 logits = tf.keras.layers.Dense(units=495,activation=tf.nn.softmax)(dropout_hidden)
 loss = tf.losses.softmax_cross_entropy(labels, logits)

3. 그런데 제가 딥러닝 레이어들에 대한 이해가 부족한 건지 이제는 shape 오류가 나서
   레이블 부분도 수정했습니다.
    if labels is not None:
        labels = tf.reshape(labels, [1,495])

그랬더니 또 오류가 나는데 해결 방법을 모르겠습니다. 
여기서 lables 가 결과값 비교하는 항목인가요?
제가 돌린 데이터는  구성이  [ 자연어 최대 250자리 한글, 4자리 숫자 코드]
이렇게 되어 있는데  그럼 tf.reshape(labels, [1,4]) 되어야 하나요?
이렇게 해도 오류가 나네요....ㅜㅜ 도움부탁 드립니다.

[오류내용] 
InvalidArgumentError: Input to reshape is a tensor with 128 values, but the requested shape has 8



 저도 앞쪽 영문 분류 예를 들어주신것처럼 3개 정로 레이어를 쌓아서 하고싶은게 최종 목표인데요.
일단 데이터도 많아서 일단 간단한걸로 돌려보고 추가로 더 하고 싶은데 지금 레이어 하나짜리 돌아가는것도 정확히 이해를 못해서 인지 오류만 팍팍 나네요 ..ㅜㅜ
이해하고 수정할 수 있는 능력이 되면 그때 수정을 해서 돌려 볼려구요....
도움 주셔서 감사합니다~~

-----------   돌린 소스코드 ------------------------------
def model_fn(features, labels, mode, params):
    TRAIN = mode == tf.estimator.ModeKeys.TRAIN
    EVAL = mode == tf.estimator.ModeKeys.EVAL
    PREDICT = mode == tf.estimator.ModeKeys.PREDICT

    embedding_layer = tf.keras.layers.Embedding(
                    VOCAB_SIZE,
                    EMB_SIZE)(features['x'])

    dropout_emb = tf.keras.layers.Dropout(rate = 0.2)(embedding_layer)
    
    conv = tf.keras.layers.Conv1D(
           filters=32,
           kernel_size=3,
           padding='same',
           activation=tf.nn.relu)(dropout_emb)
  
    pool = tf.keras.layers.GlobalMaxPool1D()(conv)

    hidden = tf.keras.layers.Dense(units=250, activation=tf.nn.relu)(pool)   


    dropout_hidden = tf.keras.layers.Dropout(rate=0.2)(hidden, training = TRAIN)
    logits = tf.keras.layers.Dense(units=495,activation=tf.nn.softmax)(dropout_hidden)
    
    if labels is not None:
        labels = tf.reshape(labels, [1,495])
        
    if TRAIN:
        global_step = tf.train.get_global_step()
        loss = tf.losses.softmax_cross_entropy(labels, logits)
        train_op = tf.train.AdamOptimizer(0.001).minimize(loss, global_step)

        return tf.estimator.EstimatorSpec(mode=mode, train_op=train_op, loss = loss)
    
    elif EVAL:
        loss = tf.losses.softmax_cross_entropy(labels, logits)
        pred = tf.nn.softmax(logits)
        accuracy = tf.metrics.accuracy(labels, tf.round(pred))
        return tf.estimator.EstimatorSpec(mode=mode, loss=loss, eval_metric_ops={'acc': accuracy})
        
    elif PREDICT:
        return tf.estimator.EstimatorSpec(
            mode=mode,
            predictions={
                'prob': tf.nn.softmax(logits),
            }
        )

---------------    결과       ------------------------




Experiment started at 22:00:56
.......................................
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from data_out/checkpoint/cnn_model\model.ckpt-168750
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 168750 into data_out/checkpoint/cnn_model\model.ckpt.


---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
~\Anaconda3\lib\site-packages\tensorflow\python\client\session.py in _do_call(self, fn, *args)
   1355     try:
-> 1356       return fn(*args)
   1357     except errors.OpError as e:

~\Anaconda3\lib\site-packages\tensorflow\python\client\session.py in _run_fn(feed_dict, fetch_list, target_list, options, run_metadata)
   1340       return self._call_tf_sessionrun(
-> 1341           options, feed_dict, fetch_list, target_list, run_metadata)
   1342 

~\Anaconda3\lib\site-packages\tensorflow\python\client\session.py in _call_tf_sessionrun(self, options, feed_dict, fetch_list, target_list, run_metadata)
   1428         self._session, options, feed_dict, fetch_list, target_list,
-> 1429         run_metadata)
   1430 

InvalidArgumentError: Input to reshape is a tensor with 128 values, but the requested shape has 8
	 [[{{node gradients/embedding/embedding_lookup_grad/Reshape_1}}]]

During handling of the above exception, another exception occurred:

InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-47-5f56f2165d34> in <module>
      3 print(".......................................")
      4 
----> 5 est.train(train_input_fn)
      6 
      7 time_end = datetime.utcnow()

~\Anaconda3\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py in train(self, input_fn, hooks, steps, max_steps, saving_listeners)
    365 
    366       saving_listeners = _check_listeners_type(saving_listeners)
--> 367       loss = self._train_model(input_fn, hooks, saving_listeners)
    368       logging.info('Loss for final step: %s.', loss)
    369       return self

~\Anaconda3\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py in _train_model(self, input_fn, hooks, saving_listeners)
   1156       return self._train_model_distributed(input_fn, hooks, saving_listeners)
   1157     else:
-> 1158       return self._train_model_default(input_fn, hooks, saving_listeners)
   1159 
   1160   def _train_model_default(self, input_fn, hooks, saving_listeners):

~\Anaconda3\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py in _train_model_default(self, input_fn, hooks, saving_listeners)
   1190       return self._train_with_estimator_spec(estimator_spec, worker_hooks,
   1191                                              hooks, global_step_tensor,
-> 1192                                              saving_listeners)
   1193 
   1194   def _train_model_distributed(self, input_fn, hooks, saving_listeners):

~\Anaconda3\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py in _train_with_estimator_spec(self, estimator_spec, worker_hooks, hooks, global_step_tensor, saving_listeners)
   1482       any_step_done = False
   1483       while not mon_sess.should_stop():
-> 1484         _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
   1485         any_step_done = True
   1486     if not any_step_done:

~\Anaconda3\lib\site-packages\tensorflow\python\training\monitored_session.py in run(self, fetches, feed_dict, options, run_metadata)
    752         feed_dict=feed_dict,
    753         options=options,
--> 754         run_metadata=run_metadata)
    755 
    756   def run_step_fn(self, step_fn):

~\Anaconda3\lib\site-packages\tensorflow\python\training\monitored_session.py in run(self, fetches, feed_dict, options, run_metadata)
   1250             feed_dict=feed_dict,
   1251             options=options,
-> 1252             run_metadata=run_metadata)
   1253       except _PREEMPTION_ERRORS as e:
   1254         logging.info(

~\Anaconda3\lib\site-packages\tensorflow\python\training\monitored_session.py in run(self, *args, **kwargs)
   1351         raise six.reraise(*original_exc_info)
   1352       else:
-> 1353         raise six.reraise(*original_exc_info)
   1354 
   1355 

~\Anaconda3\lib\site-packages\six.py in reraise(tp, value, tb)
    691             if value.__traceback__ is not tb:
    692                 raise value.with_traceback(tb)
--> 693             raise value
    694         finally:
    695             value = None

~\Anaconda3\lib\site-packages\tensorflow\python\training\monitored_session.py in run(self, *args, **kwargs)
   1336   def run(self, *args, **kwargs):
   1337     try:
-> 1338       return self._sess.run(*args, **kwargs)
   1339     except _PREEMPTION_ERRORS:
   1340       raise

~\Anaconda3\lib\site-packages\tensorflow\python\training\monitored_session.py in run(self, fetches, feed_dict, options, run_metadata)
   1409         feed_dict=feed_dict,
   1410         options=options,
-> 1411         run_metadata=run_metadata)
   1412 
   1413     for hook in self._hooks:

~\Anaconda3\lib\site-packages\tensorflow\python\training\monitored_session.py in run(self, *args, **kwargs)
   1167 
   1168   def run(self, *args, **kwargs):
-> 1169     return self._sess.run(*args, **kwargs)
   1170 
   1171   def run_step_fn(self, step_fn, raw_session, run_with_hooks):

~\Anaconda3\lib\site-packages\tensorflow\python\client\session.py in run(self, fetches, feed_dict, options, run_metadata)
    948     try:
    949       result = self._run(None, fetches, feed_dict, options_ptr,
--> 950                          run_metadata_ptr)
    951       if run_metadata:
    952         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

~\Anaconda3\lib\site-packages\tensorflow\python\client\session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1171     if final_fetches or final_targets or (handle and feed_dict_tensor):
   1172       results = self._do_run(handle, final_targets, final_fetches,
-> 1173                              feed_dict_tensor, options, run_metadata)
   1174     else:
   1175       results = []

~\Anaconda3\lib\site-packages\tensorflow\python\client\session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1348     if handle is None:
   1349       return self._do_call(_run_fn, feeds, fetches, targets, options,
-> 1350                            run_metadata)
   1351     else:
   1352       return self._do_call(_prun_fn, handle, feeds, fetches)

~\Anaconda3\lib\site-packages\tensorflow\python\client\session.py in _do_call(self, fn, *args)
   1368           pass
   1369       message = error_interpolation.interpolate(message, self._graph)
-> 1370       raise type(e)(node_def, op, message)
   1371 
   1372   def _extend_graph(self):

InvalidArgumentError: Input to reshape is a tensor with 128 values, but the requested shape has 8
	 [[node gradients/embedding/embedding_lookup_grad/Reshape_1 (defined at <ipython-input-45-d53f9a07736e>:32) ]]

Errors may have originated from an input operation.
Input Source operations connected to node gradients/embedding/embedding_lookup_grad/Reshape_1:
 IteratorGetNext (defined at <ipython-input-16-ff7dd5154d5a>:13)

**Comment by rainmaker712** [comment]
> 답변 감사드립니다.
> 사실은 지난주에 문의글을 올린 후에 코드를 일부 수정했습니다.
> 위에 말씀하신것처럼 loss 가 0 이 맞습니다. 제가 잘못적은거 같습니다.
> 
> 위에 뎃글에 책에서 제시한 소스는 이진분류로 되어 있는거라서 제가 멀티분류를 할려면
> 바꿔야 하는 부분이 있는거 같아서 수정한 부분이
> 
> 1. 기존에 sigmoid를 -> softmax로 변경
> 2. 마지막 logits 에 dense unit을 멀티 분류의 개수에 맞게 495로 수정
>    logits = tf.keras.layers.Dense(units=495,activation=tf.nn.softmax)(dropout_hidden)
>    loss = tf.losses.softmax_cross_entropy(labels, logits)
> 3. 그런데 제가 딥러닝 레이어들에 대한 이해가 부족한 건지 이제는 shape 오류가 나서
>    레이블 부분도 수정했습니다.
>    if labels is not None:
>    labels = tf.reshape(labels, [1,495])
> 
> 그랬더니 또 오류가 나는데 해결 방법을 모르겠습니다.
> 여기서 lables 가 결과값 비교하는 항목인가요?
> 제가 돌린 데이터는 구성이 [ 자연어 최대 250자리 한글, 4자리 숫자 코드]
> 이렇게 되어 있는데 그럼 tf.reshape(labels, [1,4]) 되어야 하나요?
> 이렇게 해도 오류가 나네요....ㅜㅜ 도움부탁 드립니다.
> 
> [오류내용]
> InvalidArgumentError: Input to reshape is a tensor with 128 values, but the requested shape has 8
> 
> 저도 앞쪽 영문 분류 예를 들어주신것처럼 3개 정로 레이어를 쌓아서 하고싶은게 최종 목표인데요.
> 일단 데이터도 많아서 일단 간단한걸로 돌려보고 추가로 더 하고 싶은데 지금 레이어 하나짜리 돌아가는것도 정확히 이해를 못해서 인지 오류만 팍팍 나네요 ..ㅜㅜ
> 이해하고 수정할 수 있는 능력이 되면 그때 수정을 해서 돌려 볼려구요....
> 도움 주셔서 감사합니다~~
> 
> ----------- 돌린 소스코드 ------------------------------
> def model_fn(features, labels, mode, params):
> TRAIN = mode == tf.estimator.ModeKeys.TRAIN
> EVAL = mode == tf.estimator.ModeKeys.EVAL
> PREDICT = mode == tf.estimator.ModeKeys.PREDICT
> 
> ```
> embedding_layer = tf.keras.layers.Embedding(
>                 VOCAB_SIZE,
>                 EMB_SIZE)(features['x'])
> 
> dropout_emb = tf.keras.layers.Dropout(rate = 0.2)(embedding_layer)
> 
> conv = tf.keras.layers.Conv1D(
>        filters=32,
>        kernel_size=3,
>        padding='same',
>        activation=tf.nn.relu)(dropout_emb)
> 
> pool = tf.keras.layers.GlobalMaxPool1D()(conv)
> 
> hidden = tf.keras.layers.Dense(units=250, activation=tf.nn.relu)(pool)   
> 
> 
> dropout_hidden = tf.keras.layers.Dropout(rate=0.2)(hidden, training = TRAIN)
> logits = tf.keras.layers.Dense(units=495,activation=tf.nn.softmax)(dropout_hidden)
> 
> if labels is not None:
>     labels = tf.reshape(labels, [1,495])
>     
> if TRAIN:
>     global_step = tf.train.get_global_step()
>     loss = tf.losses.softmax_cross_entropy(labels, logits)
>     train_op = tf.train.AdamOptimizer(0.001).minimize(loss, global_step)
> 
>     return tf.estimator.EstimatorSpec(mode=mode, train_op=train_op, loss = loss)
> 
> elif EVAL:
>     loss = tf.losses.softmax_cross_entropy(labels, logits)
>     pred = tf.nn.softmax(logits)
>     accuracy = tf.metrics.accuracy(labels, tf.round(pred))
>     return tf.estimator.EstimatorSpec(mode=mode, loss=loss, eval_metric_ops={'acc': accuracy})
>     
> elif PREDICT:
>     return tf.estimator.EstimatorSpec(
>         mode=mode,
>         predictions={
>             'prob': tf.nn.softmax(logits),
>         }
>     )
> ```
> 
> --------------- 결과 ------------------------
> 
> Experiment started at 22:00:56
> .......................................
> INFO:tensorflow:Calling model_fn.
> INFO:tensorflow:Done calling model_fn.
> INFO:tensorflow:Create CheckpointSaverHook.
> INFO:tensorflow:Graph was finalized.
> INFO:tensorflow:Restoring parameters from data_out/checkpoint/cnn_model\model.ckpt-168750
> INFO:tensorflow:Running local_init_op.
> INFO:tensorflow:Done running local_init_op.
> INFO:tensorflow:Saving checkpoints for 168750 into data_out/checkpoint/cnn_model\model.ckpt.
> 
> InvalidArgumentError Traceback (most recent call last)
> ~\Anaconda3\lib\site-packages\tensorflow\python\client\session.py in _do_call(self, fn, *args)
> 1355 try:
> -> 1356 return fn(*args)
> 1357 except errors.OpError as e:
> 
> ~\Anaconda3\lib\site-packages\tensorflow\python\client\session.py in _run_fn(feed_dict, fetch_list, target_list, options, run_metadata)
> 1340 return self._call_tf_sessionrun(
> -> 1341 options, feed_dict, fetch_list, target_list, run_metadata)
> 1342
> 
> ~\Anaconda3\lib\site-packages\tensorflow\python\client\session.py in _call_tf_sessionrun(self, options, feed_dict, fetch_list, target_list, run_metadata)
> 1428 self._session, options, feed_dict, fetch_list, target_list,
> -> 1429 run_metadata)
> 1430
> 
> InvalidArgumentError: Input to reshape is a tensor with 128 values, but the requested shape has 8
> [[{{node gradients/embedding/embedding_lookup_grad/Reshape_1}}]]
> 
> During handling of the above exception, another exception occurred:
> 
> InvalidArgumentError Traceback (most recent call last)
> in 
> 3 print(".......................................")
> 4
> ----> 5 est.train(train_input_fn)
> 6
> 7 time_end = datetime.utcnow()
> 
> ~\Anaconda3\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py in train(self, input_fn, hooks, steps, max_steps, saving_listeners)
> 365
> 366 saving_listeners = _check_listeners_type(saving_listeners)
> --> 367 loss = self._train_model(input_fn, hooks, saving_listeners)
> 368 logging.info('Loss for final step: %s.', loss)
> 369 return self
> 
> ~\Anaconda3\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py in _train_model(self, input_fn, hooks, saving_listeners)
> 1156 return self._train_model_distributed(input_fn, hooks, saving_listeners)
> 1157 else:
> -> 1158 return self._train_model_default(input_fn, hooks, saving_listeners)
> 1159
> 1160 def _train_model_default(self, input_fn, hooks, saving_listeners):
> 
> ~\Anaconda3\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py in _train_model_default(self, input_fn, hooks, saving_listeners)
> 1190 return self._train_with_estimator_spec(estimator_spec, worker_hooks,
> 1191 hooks, global_step_tensor,
> -> 1192 saving_listeners)
> 1193
> 1194 def _train_model_distributed(self, input_fn, hooks, saving_listeners):
> 
> ~\Anaconda3\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py in _train_with_estimator_spec(self, estimator_spec, worker_hooks, hooks, global_step_tensor, saving_listeners)
> 1482 any_step_done = False
> 1483 while not mon_sess.should_stop():
> -> 1484 _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
> 1485 any_step_done = True
> 1486 if not any_step_done:
> 
> ~\Anaconda3\lib\site-packages\tensorflow\python\training\monitored_session.py in run(self, fetches, feed_dict, options, run_metadata)
> 752 feed_dict=feed_dict,
> 753 options=options,
> --> 754 run_metadata=run_metadata)
> 755
> 756 def run_step_fn(self, step_fn):
> 
> ~\Anaconda3\lib\site-packages\tensorflow\python\training\monitored_session.py in run(self, fetches, feed_dict, options, run_metadata)
> 1250 feed_dict=feed_dict,
> 1251 options=options,
> -> 1252 run_metadata=run_metadata)
> 1253 except _PREEMPTION_ERRORS as e:
> 1254 logging.info(
> 
> ~\Anaconda3\lib\site-packages\tensorflow\python\training\monitored_session.py in run(self, *args, **kwargs)
> 1351 raise six.reraise(*original_exc_info)
> 1352 else:
> -> 1353 raise six.reraise(*original_exc_info)
> 1354
> 1355
> 
> ~\Anaconda3\lib\site-packages\six.py in reraise(tp, value, tb)
> 691 if value.**traceback** is not tb:
> 692 raise value.with_traceback(tb)
> --> 693 raise value
> 694 finally:
> 695 value = None
> 
> ~\Anaconda3\lib\site-packages\tensorflow\python\training\monitored_session.py in run(self, *args, **kwargs)
> 1336 def run(self, *args, **kwargs):
> 1337 try:
> -> 1338 return self._sess.run(*args, **kwargs)
> 1339 except _PREEMPTION_ERRORS:
> 1340 raise
> 
> ~\Anaconda3\lib\site-packages\tensorflow\python\training\monitored_session.py in run(self, fetches, feed_dict, options, run_metadata)
> 1409 feed_dict=feed_dict,
> 1410 options=options,
> -> 1411 run_metadata=run_metadata)
> 1412
> 1413 for hook in self._hooks:
> 
> ~\Anaconda3\lib\site-packages\tensorflow\python\training\monitored_session.py in run(self, *args, **kwargs)
> 1167
> 1168 def run(self, *args, **kwargs):
> -> 1169 return self._sess.run(*args, **kwargs)
> 1170
> 1171 def run_step_fn(self, step_fn, raw_session, run_with_hooks):
> 
> ~\Anaconda3\lib\site-packages\tensorflow\python\client\session.py in run(self, fetches, feed_dict, options, run_metadata)
> 948 try:
> 949 result = self._run(None, fetches, feed_dict, options_ptr,
> --> 950 run_metadata_ptr)
> 951 if run_metadata:
> 952 proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)
> 
> ~\Anaconda3\lib\site-packages\tensorflow\python\client\session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
> 1171 if final_fetches or final_targets or (handle and feed_dict_tensor):
> 1172 results = self._do_run(handle, final_targets, final_fetches,
> -> 1173 feed_dict_tensor, options, run_metadata)
> 1174 else:
> 1175 results = []
> 
> ~\Anaconda3\lib\site-packages\tensorflow\python\client\session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
> 1348 if handle is None:
> 1349 return self._do_call(_run_fn, feeds, fetches, targets, options,
> -> 1350 run_metadata)
> 1351 else:
> 1352 return self._do_call(_prun_fn, handle, feeds, fetches)
> 
> ~\Anaconda3\lib\site-packages\tensorflow\python\client\session.py in _do_call(self, fn, *args)
> 1368 pass
> 1369 message = error_interpolation.interpolate(message, self._graph)
> -> 1370 raise type(e)(node_def, op, message)
> 1371
> 1372 def _extend_graph(self):
> 
> InvalidArgumentError: Input to reshape is a tensor with 128 values, but the requested shape has 8
> [[node gradients/embedding/embedding_lookup_grad/Reshape_1 (defined at :32) ]]
> 
> Errors may have originated from an input operation.
> Input Source operations connected to node gradients/embedding/embedding_lookup_grad/Reshape_1:
> IteratorGetNext (defined at :13)

**"조금 더 정확히 알기 위해서, print(label) print(logit)쪽을 찍어봐 주실수 있나요?"**
이 부분을 주셔야, 검토가 될 듯 합니다. 추가로 각 shape도 부탁 드려요.

+ loss가 0이라는건 오버피팅 되있는건지 몰라도, 완벽하게 맞춘다는건데 이해가 가지 않습니다.
loss가 0이라면 학습셋의 정확도는 100%가 나와야 하는거 아닌가요? 그게 아니라면 아래 제가 말씀드린 것 처럼 다양한 이유가 있을 듯 합니다.

This can be caused by:
- not shuffled data
- bad labels assigned to training data
- there is sth wrong with your data (random values in training data etc.)

https://groups.google.com/forum/#!topic/caffe-users/vPZUcaooed4
