### ISSUE TITLE
열심히 책을 보고 공부하고 있는데 설명이 부족한 부분이 많네요....

### ISSUE THREAD

**Issue by cocoten** [NLP-kr/tensorflow-ml-nlp#33]
전체적으로 책을 다 읽어보고 실습을 해보고 응용도 해 보고 있는데요.

소스코드에 대한 충분한 설명이 좀 부족합니다.

저는 일단 CNN 쪽에 관심이 많아서 CNN을 먼저 봤는데요.

보다보면 설명이 자세하지 않아서 보면 대부분 앞부분에 설명이 있다라고 되어있고 설명이 없이

넘어가는 것이 많은거 같습니다. 특히 임베딩사이즈,배치사이즈,에폭, Dence Unit의 개수,Dropout 

rate 등 왜 이 숫자를 썼는지 알고싶은데 책을 앞뒤 봐도 잘 이해가 안되네요...

그리고 227페이지 상단에  " 넘파이 배열은 지정한 경로에 nsmc_train_input.npy 와 nsmc_train_input.npy 로 각각 저장된다." 라는 문구가 있는데요

nsmc_train_input.npy 이거가 2번 나오는게 맞나요? 두번째 nsmc_train_input.npy 는
nsmc_train_label.npy 인가요? 아니면 test_train_input.npy 인가요?

**Comment by reniew** [comment]
첫 번째 질문해주신 하이퍼 파라미터 관련해서는 우선 저희가 제시한 하이퍼 파라미터는 optimal 한 하이퍼 파라미터는  아닙니다. 기준으로 제시한 하이퍼 파라미터이고, 독자분들께서 저희가 제시한 모델링 방법을 기반으로 하이퍼 파라미터 튜닝을 하는 것을 의도했습니다!

그리고 두번째 지적해주신 `nsmc_train_input.npy` 는 말씀하신대로가 맞습니다. 오탈자인것 같습니다. 지적해주셔서 감사합니다!

**Comment by cocoten** [comment]
답변 감사합니다. 의도하신 내용은 충분히 이해를 합니다. 저같은 초보자는 기존에 제시한 하이퍼파라메터에 대한 충분한 이해가 없으니 이걸 튜닝을 어떻게 해야할지가 좀 막막하더라구요. 좀 바꿔서 성능을 높여볼려고 하면 계속 오류만 나서 성능을 높이기 보다는 원인 찾는일반 생기는거 같습니아. ^^
