### ISSUE TITLE
seq2seq 내용에 대해 질문합니다.

### ISSUE THREAD

**Issue by soosvin** [NLP-kr/tensorflow-ml-nlp#7]
책에 나온 seq2seq 코드의 경우 디코더 부분에 인풋값을 넣어주는데 이 경우는 teacher forcing을 100% 사용하는 것인가요?
텐서플로우 내에서는 이렇게 teacher forcing이 자동으로 적용되는 것인지 궁금합니다.
그리고 학습이 끝난 후 inference하는 과정에서는 teacher forcing이 사용되면 안되는걸로 알고 있는데 만약 위와 같이 자동으로 적용이 된다면 현 코드에서는 <start> <pad> <pad> 이런식으로 들어 갈 것 같아서 제대로나오지 않을 것 같은데 이해가 잘 되지 않네요.
오히려 그 전 step에서 나온 값이 들어가야 된다고 생각하는데, 이 점에 대해서 설명해주시면 감사하겠습니다.

**Comment by changwookjun** [comment]
안녕하세요  soosvin님
"책에 나온 seq2seq 코드의 경우 디코더 부분에 인풋값을 넣어주는데 이 경우는 teacher forcing을 100% 사용하는 것인가요?"
**책 본문에 나온 내용은 teacher forcing 100%가 맞습니다.**
"텐서플로우 내에서는 이렇게 teacher forcing이 자동으로 적용되는 것인지 궁금"
**텐서플로우 내에서 자동으로 teacher forcing을 지원하는 API가 있는지는 모르겠으나 책에 소스는 자동으로 하지 않습니다.**
"학습이 끝난 후 inference하는 과정에서는 teacher forcing이 사용되면 안되는걸"
**맞습니다.**

책 본문에 나온 내용은 간략하게 모델링과 seq2seq을 간소하게 동작 구조를 설명하기 위해서 표현 되었으면 soosvin님 말씀하신 teacher forcing 사용 방법은  부록편의 seq2seq 을 보시면 학습시 teacher forcing 확률값에 의해서 정답을 입력으로 넣을지 이전 step 에 나온값을 입력으로 넣을지 결정하면 inference시에는 teacher forcing을 하지 않고 이전 step에서 나온값을 100%사용합니다. 

질문 감사드립니다. ^^

**Comment by soosvin** [comment]
changwookjun님 감사합니다.
추가로 질문 하나만 더 하겠습니다.
transformer의 경우도 마찬가지로 teacher forcing을 사용한 건가요?
또한 inference 과정에서도 teacher forcing이 사용되는 것 같은데 inference 과정에서는 원래의 경우에는 teacher forcing을 사용 안하고 그 전 output을 넣어주는게 맞는지 궁금합니다.

**Comment by changwookjun** [comment]
transformer는 teacher forcing의 개념이 없습니다. RNN에서 teacher forcing은 정답의 사용 유무라고 한다.  transformer는 소스에서 보시면 학습시에는 정답을 넣어 주는데 decoder에서 마스크를 하여 예측할 값을 가리도록 하며 Inference에서는 예측한 token을 다시 입력으로 넣어 주면서 반복적으로 실행하는것을 볼수 있습니다. 
transformer에서는 teacher forcing이라는 말을 쓰는것을 못봐서 두개를 매칭 시켜서 사용하는것은 혼선을 줄거 같습니다.

**Comment by Taekyoon** [comment]
현 이슈에 대해서 22일이 지났습니다. 
더 진행할 내용이 없으면 이슈 스레드 #7를 닫을까 합니다.
