### ISSUE TITLE
책 잘보고 있습니다.

### ISSUE THREAD

**Issue by parkskwan** [NLP-kr/tensorflow-ml-nlp#8]
새로운 종류의 '챗봇 만들기'도 기대 하겠습니다.

**Comment by reniew** [comment]
네 감사합니다.

혹시 기존의 이슈는 해결하신건가요?

**Comment by parkskwan** [comment]
안녕하세요,

해결 했습니다.

정확한 이유는 알 수 없지만   
저의 경우는 GPU 사용 설정 유무에 영향을 받는 것 이었습니다.  GPU를 사용한다고 설정하면 에러 발생이 없어졌습니다.

아마도 제가 작가님 책의 앞부분을 제대로 읽지 않아서 이겠지요?

감사합니다.

**Comment by Taekyoon** [comment]
이슈에 대해서 진행한지 19일이 지났습니다.
혹시 더 진행할 내용이 없으면 이슈 스레드 #8에 대해서 닫고자 합니다.
