### ISSUE TITLE
[도서] 책에 오타가 있어 보입니다.

### ISSUE THREAD

**Issue by ghost** [NLP-kr/tensorflow-ml-nlp#9]
안녕하세요. 도서를 구입하여 열심히 정독하고 있습니다.

125페이지에 [그림 3.15]에서
euclidean distance는 검정색이고,
manhattan distance는 붉은색 아닌지요.

wikipedia그림에서 이미지의 색이 바뀌면서
발생한 오타 같습니다만...

확인 요청드립니다.

**Comment by changwookjun** [comment]
2쇄에 수정 되어서 나올 예정 입니다. 

이렇게 관심 가지시고 글 올려 주셔서 감사합니다. 

좋은 하루 되세요 .

**Comment by changwookjun** [comment]
> 안녕하세요. 도서를 구입하여 열심히 정독하고 있습니다.
> 
> 125페이지에 [그림 3.15]에서
> euclidean distance는 검정색이고,
> manhattan distance는 붉은색 아닌지요.
> 
> wikipedia그림에서 이미지의 색이 바뀌면서
> 발생한 오타 같습니다만...
> 
> 확인 요청드립니다.
